[[mgr.prepend_keymap]]
desc = "Maximize or restore the preview pane"
on = "T"
run = "plugin --sync max-preview"

[[mgr.prepend_keymap]]
desc = "Chmod on selected files"
on = ["c", "m"]
run = "plugin chmod"

[[mgr.prepend_keymap]]
desc = "Cd to note"
on = ["g", "o"]
run = "cd $OBNOTE"

[[mgr.prepend_keymap]]
desc = "Cd to nvim config"
on = ["g", "v"]
run = "cd ~/.config/nvim"

[[mgr.prepend_keymap]]
desc = "Cd to nixos config"
on = ["g", "n"]
run = "cd ~/nixos-config"

[[mgr.prepend_keymap]]
desc = "Lazygit"
on = ["<C-g>"]
run = "shell --confirm --block lazygit"

