[mgr]
show_hidden = false

[[opener.edit]]
block = true
for = "unix"
run = "$EDITOR \"$@\""

[[opener.edit]]
block = true
desc = "nvim"
for = "windows"
run = "nvim %*"

[preview]
max_height = 1000
max_width = 1000


[[plugin.prepend_previewers]]
name = "*.md"
run  = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"'
